version: '3.8'

services:
  vue:
    build: .
    ports:
      - 8080:5173
    volumes:
      - .:/website
    working_dir: /website
    command: pnpm dev --host

  test:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./dist:/usr/share/nginx/html
