version: '3'

services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:5173
    volumes:
      - .:/website
      - pnpm-store:/website/.pnpm-store
      - node_modules:/website/node_modules
    working_dir: /website
    command: sh -c "pnpm install && pnpm dev --host"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80

volumes:
  pnpm-store:
  node_modules:
